# This file was auto-generated by the Nova compiler.
# Do not edit this file manually.

defmodule Nova.Compiler.CstLayout do
  # import Prelude

  # import Data.List

  # import Data.Maybe

  # import Data.Tuple

  # import Nova.Compiler.Cst

  # @type layout_stack :: list()((tuple()(source_pos())(layout_delim())))

  # Data type: LayoutDelim
  def lyt_root(), do: :lyt_root
  def lyt_top_decl(), do: :lyt_top_decl
  def lyt_top_decl_head(), do: :lyt_top_decl_head
  def lyt_decl_guard(), do: :lyt_decl_guard
  def lyt_case(), do: :lyt_case
  def lyt_case_binders(), do: :lyt_case_binders
  def lyt_case_guard(), do: :lyt_case_guard
  def lyt_lambda_binders(), do: :lyt_lambda_binders
  def lyt_paren(), do: :lyt_paren
  def lyt_brace(), do: :lyt_brace
  def lyt_square(), do: :lyt_square
  def lyt_if(), do: :lyt_if
  def lyt_then(), do: :lyt_then
  def lyt_property(), do: :lyt_property
  def lyt_forall(), do: :lyt_forall
  def lyt_tick(), do: :lyt_tick
  def lyt_let(), do: :lyt_let
  def lyt_let_stmt(), do: :lyt_let_stmt
  def lyt_where(), do: :lyt_where
  def lyt_of(), do: :lyt_of
  def lyt_do(), do: :lyt_do
  def lyt_ado(), do: :lyt_ado

  # derive instance Eq layout_delim()

  # derive instance Ord layout_delim()



  def root_layout_delim() do
    :lyt_root
  end



  def is_indented(lyt) do
    case lyt do
      :lyt_let -> true
      :lyt_let_stmt -> true
      :lyt_where -> true
      :lyt_of -> true
      :lyt_do -> true
      :lyt_ado -> true
      _ -> false
    end
  end



  def current_indent_go(stk) do
    case stk do
      [{:tuple, pos, lyt} | rest] -> if is_indented(lyt) do
          {:just, pos}
        else
          current_indent_go(rest)
        end
      _ -> :nothing
    end
  end



  def current_indent(auto_arg0) do
    current_indent_go(auto_arg0)
  end



  def is_top_decl(tok_pos, stack) do
    case stack do
      [{:tuple, lyt_pos, lyt1} | rest] -> if (lyt1 == :lyt_where) do
          case rest do
            [{:tuple, _, lyt2} | []] -> ((lyt2 == :lyt_root) and (tok_pos.column == lyt_pos.column))
            _ -> false
          end
        else
          false
        end
      _ -> false
    end
  end



  def lyt_token(pos, value) do
    %{range: %{start: pos, end_: pos}, leading_comments: [], trailing_comments: [], value: value}
  end



  def insert_layout(src, next_pos, stack) do
    
      tok_pos = src.range.start
      tok = src.value
      find_indented = Nova.Runtime.fix(fn find_indented -> fn auto_arg0 -> case auto_arg0 do
        [] -> :nothing
        ([({:tuple, _, lyt}) = item | rest]) -> if is_indented(lyt) do
  {:just, item}
else
  (raise "CodeGen error: Missing arity for local variable 'findIndented'")
end
      end end end)
      insert_token = fn token -> fn ({:tuple, stk, acc}) -> {:tuple, stk, (Nova.Runtime.append(acc, ([({:tuple, token, stk}) | []])))} end end
      push_stack = fn lyt_pos -> fn lyt -> fn ({:tuple, stk, acc}) -> {:tuple, ([{:tuple, lyt_pos, lyt} | stk]), acc} end end end
      pop_stack = fn p -> fn state -> case state do
        {:tuple, ([{:tuple, _, lyt} | stk_prime]), acc} -> if (raise "CodeGen error: Missing arity for local variable 'p'") do
            {:tuple, stk_prime, acc}
          else
            state
          end
        _ -> state
      end end end
      indented_p = fn auto_p0 -> Prelude.const((&is_indented/1), auto_p0) end
      in_p = fn auto_arg0 -> fn auto_arg1 -> case {auto_arg0, auto_arg1} do
        {_, :lyt_let} -> false
        {_, :lyt_ado} -> false
        {_, lyt} -> is_indented(lyt)
      end end end
      guard_p = fn auto_arg0 -> case auto_arg0 do
        :lyt_case_binders -> true
        :lyt_case_guard -> true
        :lyt_lambda_binders -> true
        _ -> false
      end end
      equals_p = fn auto_arg0 -> fn auto_arg1 -> case {auto_arg0, auto_arg1} do
        {_, :lyt_where} -> true
        {_, :lyt_let} -> true
        {_, :lyt_let_stmt} -> true
        {_, _} -> false
      end end end
      insert_start = fn lyt -> fn ({:tuple, stk, _}) = state -> case (raise "CodeGen error: Missing arity for local variable 'findIndented'") do
        {:just, ({:tuple, pos, _})} -> if (next_pos.column <= pos.column) do
            state
          else
            ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(((raise "CodeGen error: Missing arity for local variable 'pushStack'")).(state))
          end
        _ -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(((raise "CodeGen error: Missing arity for local variable 'pushStack'")).(state))
      end end end
      insert_end = fn indent -> (raise "CodeGen error: Missing arity for local variable 'insertToken'") end
      collapse = fn p -> 
        go = Nova.Runtime.fix(fn go -> fn state -> case state do
          {:tuple, ([{:tuple, lyt_pos, lyt} | stk_prime]), acc} -> if (raise "CodeGen error: Missing arity for local variable 'p'") do
              (raise "CodeGen error: Missing arity for local variable 'go'")
            else
              state
            end
          _ -> state
        end  end end)
        go end
      offside_p = fn lyt_pos -> fn lyt -> (is_indented(lyt) and (tok_pos.column < lyt_pos.column)) end end
      offside_end_p = fn lyt_pos -> fn lyt -> (is_indented(lyt) and (tok_pos.column <= lyt_pos.column)) end end
      sep_p = fn lyt_pos -> ((tok_pos.column == lyt_pos.column) and (tok_pos.line != lyt_pos.line)) end
      indent_sep_p = fn lyt_pos -> fn lyt -> (is_indented(lyt) and (raise "CodeGen error: Missing arity for local variable 'sepP'")) end end
      where_p = fn auto_arg0 -> fn auto_arg1 -> case {auto_arg0, auto_arg1} do
        {_, :lyt_do} -> true
        {lyt_pos, lyt} -> (raise "CodeGen error: Missing arity for local variable 'offsideEndP'")
      end end end
      let_next = fn ({:tuple, stk_prime, _}) = state_prime -> case stk_prime do
        [{:tuple, p, :lyt_do} | _] -> if (p.column == tok_pos.column) do
            ((raise "CodeGen error: Missing arity for local variable 'insertStart'")).(state_prime)
          else
            ((raise "CodeGen error: Missing arity for local variable 'insertStart'")).(state_prime)
          end
        [{:tuple, p, :lyt_ado} | _] -> if (p.column == tok_pos.column) do
            ((raise "CodeGen error: Missing arity for local variable 'insertStart'")).(state_prime)
          else
            ((raise "CodeGen error: Missing arity for local variable 'insertStart'")).(state_prime)
          end
        _ -> ((raise "CodeGen error: Missing arity for local variable 'insertStart'")).(state_prime)
      end end
      arrow_p = fn auto_arg0 -> fn auto_arg1 -> case {auto_arg0, auto_arg1} do
        {_, :lyt_do} -> true
        {_, :lyt_of} -> false
        {lyt_pos, lyt} -> (raise "CodeGen error: Missing arity for local variable 'offsideEndP'")
      end end end
      insert_sep = fn ({:tuple, stk, acc}) = state -> 
        sep_tok = lyt_token(tok_pos, (Nova.Compiler.Cst.tok_layout_sep(tok_pos.column)))
        case stk do
  [{:tuple, lyt_pos, :lyt_top_decl} | stk_prime] -> if (raise "CodeGen error: Missing arity for local variable 'sepP'") do
      ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).({:tuple, stk_prime, acc})
    else
      state
    end
  [{:tuple, lyt_pos, :lyt_top_decl_head} | stk_prime] -> if (raise "CodeGen error: Missing arity for local variable 'sepP'") do
      ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).({:tuple, stk_prime, acc})
    else
      state
    end
  [{:tuple, lyt_pos, lyt} | _] -> if (raise "CodeGen error: Missing arity for local variable 'indentSepP'") do
      case lyt do
        :lyt_of -> ((raise "CodeGen error: Missing arity for local variable 'pushStack'")).(((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(state))
        _ -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(state)
      end
    else
      state
    end
  _ -> state
end end
      insert_default = fn state -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).((insert_sep).(((raise "CodeGen error: Missing arity for local variable 'collapse'")).(state))) end
      insert_kw_property = fn k -> fn state -> case (insert_default).(state) do
        {:tuple, ([{:tuple, _, :lyt_property} | stk_prime]), acc_prime} -> {:tuple, stk_prime, acc_prime}
        state_prime -> (raise "CodeGen error: Missing arity for local variable 'k'")
      end end end
      insert = fn state -> case tok do
        {:tok_lower_name, :nothing, "data"} -> case (insert_default).(state) do
            ({:tuple, stk_prime, _}) = state_prime ->
              if is_top_decl(tok_pos, stk_prime) do
                ((raise "CodeGen error: Missing arity for local variable 'pushStack'")).(state_prime)
              end
            state_prime -> ((raise "CodeGen error: Missing arity for local variable 'popStack'")).(state_prime)
          end
        {:tok_lower_name, :nothing, "class"} -> case (insert_default).(state) do
            ({:tuple, stk_prime, _}) = state_prime ->
              if is_top_decl(tok_pos, stk_prime) do
                ((raise "CodeGen error: Missing arity for local variable 'pushStack'")).(state_prime)
              end
            state_prime -> ((raise "CodeGen error: Missing arity for local variable 'popStack'")).(state_prime)
          end
        {:tok_lower_name, :nothing, "where"} -> case stack do
            [{:tuple, _, :lyt_top_decl_head} | stk_prime] -> ((raise "CodeGen error: Missing arity for local variable 'insertStart'")).(((raise "CodeGen error: Missing arity for local variable 'insertToken'")).({:tuple, stk_prime, (Data.Tuple.snd(state))}))
            [{:tuple, _, :lyt_property} | stk_prime] -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).({:tuple, stk_prime, (Data.Tuple.snd(state))})
            _ -> ((raise "CodeGen error: Missing arity for local variable 'insertStart'")).(((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(((raise "CodeGen error: Missing arity for local variable 'collapse'")).(state)))
          end
        {:tok_lower_name, :nothing, "in"} -> case (raise "CodeGen error: Missing arity for local variable 'collapse'") do
            {:tuple, ([({:tuple, pos1, :lyt_let_stmt}) | [({:tuple, pos2, :lyt_ado}) | stk_prime]]), acc_prime} -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(((raise "CodeGen error: Missing arity for local variable 'insertEnd'")).(((raise "CodeGen error: Missing arity for local variable 'insertEnd'")).({:tuple, stk_prime, acc_prime})))
            {:tuple, ([{:tuple, pos1, lyt} | stk_prime]), acc_prime} -> if is_indented(lyt) do
                ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(((raise "CodeGen error: Missing arity for local variable 'insertEnd'")).({:tuple, stk_prime, acc_prime}))
              else
                ((raise "CodeGen error: Missing arity for local variable 'popStack'")).((insert_default).(state))
              end
            _ -> ((raise "CodeGen error: Missing arity for local variable 'popStack'")).((insert_default).(state))
          end
        {:tok_lower_name, :nothing, "let"} -> ((raise "CodeGen error: Missing arity for local variable 'insertKwProperty'")).(state)
        {:tok_lower_name, _, "do"} -> ((raise "CodeGen error: Missing arity for local variable 'insertKwProperty'")).(state)
        {:tok_lower_name, _, "ado"} -> ((raise "CodeGen error: Missing arity for local variable 'insertKwProperty'")).(state)
        {:tok_lower_name, :nothing, "case"} -> ((raise "CodeGen error: Missing arity for local variable 'insertKwProperty'")).(state)
        {:tok_lower_name, :nothing, "of"} -> case (raise "CodeGen error: Missing arity for local variable 'collapse'") do
            {:tuple, ([{:tuple, _, :lyt_case} | stk_prime]), acc_prime} -> ((raise "CodeGen error: Missing arity for local variable 'pushStack'")).(((raise "CodeGen error: Missing arity for local variable 'insertStart'")).(((raise "CodeGen error: Missing arity for local variable 'insertToken'")).({:tuple, stk_prime, acc_prime})))
            state_prime -> ((raise "CodeGen error: Missing arity for local variable 'popStack'")).((insert_default).(state_prime))
          end
        {:tok_lower_name, :nothing, "if"} -> ((raise "CodeGen error: Missing arity for local variable 'insertKwProperty'")).(state)
        {:tok_lower_name, :nothing, "then"} -> case ((raise "CodeGen error: Missing arity for local variable 'collapse'")).(state) do
            {:tuple, ([{:tuple, _, :lyt_if} | stk_prime]), acc_prime} -> ((raise "CodeGen error: Missing arity for local variable 'pushStack'")).(((raise "CodeGen error: Missing arity for local variable 'insertToken'")).({:tuple, stk_prime, acc_prime}))
            _ -> ((raise "CodeGen error: Missing arity for local variable 'popStack'")).((insert_default).(state))
          end
        {:tok_lower_name, :nothing, "else"} -> case ((raise "CodeGen error: Missing arity for local variable 'collapse'")).(state) do
            {:tuple, ([{:tuple, _, :lyt_then} | stk_prime]), acc_prime} -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).({:tuple, stk_prime, acc_prime})
            _ -> case ((raise "CodeGen error: Missing arity for local variable 'collapse'")).(state) do
                ({:tuple, stk_prime, _}) = state_prime ->
                  if is_top_decl(tok_pos, stk_prime) do
                    ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(state_prime)
                  end
                state_prime -> ((raise "CodeGen error: Missing arity for local variable 'popStack'")).(((raise "CodeGen error: Missing arity for local variable 'insertToken'")).((insert_sep).(state_prime)))
              end
          end
        :tok_forall -> ((raise "CodeGen error: Missing arity for local variable 'insertKwProperty'")).(state)
        :tok_backslash -> ((raise "CodeGen error: Missing arity for local variable 'pushStack'")).((insert_default).(state))
        :tok_right_arrow -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(((raise "CodeGen error: Missing arity for local variable 'popStack'")).(((raise "CodeGen error: Missing arity for local variable 'collapse'")).(state)))
        :tok_equals -> case ((raise "CodeGen error: Missing arity for local variable 'collapse'")).(state) do
            {:tuple, ([{:tuple, _, :lyt_decl_guard} | stk_prime]), acc_prime} -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).({:tuple, stk_prime, acc_prime})
            _ -> (insert_default).(state)
          end
        :tok_pipe -> case (raise "CodeGen error: Missing arity for local variable 'collapse'") do
            ({:tuple, ([{:tuple, _, :lyt_of} | _]), _}) = state_prime -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(((raise "CodeGen error: Missing arity for local variable 'pushStack'")).(state_prime))
            ({:tuple, ([{:tuple, _, :lyt_let} | _]), _}) = state_prime -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(((raise "CodeGen error: Missing arity for local variable 'pushStack'")).(state_prime))
            ({:tuple, ([{:tuple, _, :lyt_let_stmt} | _]), _}) = state_prime -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(((raise "CodeGen error: Missing arity for local variable 'pushStack'")).(state_prime))
            ({:tuple, ([{:tuple, _, :lyt_where} | _]), _}) = state_prime -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(((raise "CodeGen error: Missing arity for local variable 'pushStack'")).(state_prime))
            _ -> (insert_default).(state)
          end
        :tok_tick -> case ((raise "CodeGen error: Missing arity for local variable 'collapse'")).(state) do
            {:tuple, ([{:tuple, _, :lyt_tick} | stk_prime]), acc_prime} -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).({:tuple, stk_prime, acc_prime})
            _ -> ((raise "CodeGen error: Missing arity for local variable 'pushStack'")).(((raise "CodeGen error: Missing arity for local variable 'insertToken'")).((insert_sep).(((raise "CodeGen error: Missing arity for local variable 'collapse'")).(state))))
          end
        :tok_comma -> case ((raise "CodeGen error: Missing arity for local variable 'collapse'")).(state) do
            ({:tuple, ([{:tuple, _, :lyt_brace} | _]), _}) = state_prime -> ((raise "CodeGen error: Missing arity for local variable 'pushStack'")).(((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(state_prime))
            state_prime -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(state_prime)
          end
        :tok_dot -> case (insert_default).(state) do
            {:tuple, ([{:tuple, _, :lyt_forall} | stk_prime]), acc_prime} -> {:tuple, stk_prime, acc_prime}
            state_prime -> ((raise "CodeGen error: Missing arity for local variable 'pushStack'")).(state_prime)
          end
        :tok_left_paren -> ((raise "CodeGen error: Missing arity for local variable 'pushStack'")).((insert_default).(state))
        :tok_left_brace -> ((raise "CodeGen error: Missing arity for local variable 'pushStack'")).(((raise "CodeGen error: Missing arity for local variable 'pushStack'")).((insert_default).(state)))
        :tok_left_square -> ((raise "CodeGen error: Missing arity for local variable 'pushStack'")).((insert_default).(state))
        :tok_right_paren -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(((raise "CodeGen error: Missing arity for local variable 'popStack'")).(((raise "CodeGen error: Missing arity for local variable 'collapse'")).(state)))
        :tok_right_brace -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(((raise "CodeGen error: Missing arity for local variable 'popStack'")).(((raise "CodeGen error: Missing arity for local variable 'popStack'")).(((raise "CodeGen error: Missing arity for local variable 'collapse'")).(state))))
        :tok_right_square -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).(((raise "CodeGen error: Missing arity for local variable 'popStack'")).(((raise "CodeGen error: Missing arity for local variable 'collapse'")).(state)))
        {:tok_string, _, _} -> ((raise "CodeGen error: Missing arity for local variable 'popStack'")).((insert_default).(state))
        {:tok_lower_name, :nothing, _} -> ((raise "CodeGen error: Missing arity for local variable 'popStack'")).((insert_default).(state))
        {:tok_operator, _, _} -> ((raise "CodeGen error: Missing arity for local variable 'insertToken'")).((insert_sep).(((raise "CodeGen error: Missing arity for local variable 'collapse'")).(state)))
        _ -> (insert_default).(state)
      end end
      (raise "CodeGen error: Missing arity for local variable 'insert'")
  end
end
